theme: minima
#remote_theme: jekyll/minima
title: Vizualizácia dát · 1-DAV-105 · LS 2024/25

exclude: [README.md]

header_pages:
  - index.md
  - Rules.md
  - Groups.md
  - Projects.md
  - Exam.md
  - Contact.md

